/cml2023/start_cml: "Start carry my luggage"
/cml2023/which_bag: "Which bag should I grasp?"
/cml2023/ok: "Ok."
/cml2023/right_bag: "I will grasp the bag on the right as seen from you"
/cml2023/left_bag: "I will grasp the bag on the left as seen from you"
/cml2023/follow_you: "I'll follow you."
/cml2023/follow_lost: "I lost sight of you. Wait for me please."
/cml2023/car_question: "Is this the location of the car?"
/cml2023/follow_continue: "Ok, continue to follow."
/cml2023/give_bag: "Here you are"
/cml2023/return: "Return to start position"
/cml2023/finish_cml: "Finish carry my luggage. Thank you very much"

